import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/ui/Navbar/Navbar";
import Footer from "../../components/ui/Footer/Footer";
import Context from "../../components/ui/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-black loading">
                <Context>
                    <Navbar />
                    <main
                        id="skip"
                        className="min-h-[calc(100dvh-4rem)] md:min-h[calc(100dvh-5rem)]"
                    >
                        {children}
                    </main>
                    <Footer />
                </Context>
            </body>
        </html>
    );
}
